name: Build and publish site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "pub" branch
  push:
    branches: [ "pub" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Build
        run: nix build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          # Path of the directory containing the static assets.
          path: result
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
          
          
